<p>Hi,</p>
<p>I work for eTangerine Technologies and manage sales operations of our Toronto office covering North America region. I came across your advertisement in craigslist looking for a {{ $job_position }}. I felt that you might be interested in our services and decided to contact you. </p>
<p>We can help you set up an <b>offshore team</b> working in your time zone, reducing your cost by 50-60%. And we can do this without any risk to your business. Just set up your team and try it out <b>XnumdaysX days for free </b>. If you feel that it is not working out, you can cancel anytime. No questions asked. </p>
<p>We can get you the best people for the job. You can select the right person from a pool of good candidates. In addition, we offer very flexible engagement models: monthly, quarterly or any model you feel comfortable with. </p>
<p>If this is something that you are interested in, let’s set up a quick call to discuss further. You can email me at <a href="mailto:someone@example.com">madhum@etangerine.org</a> or call me at +1 314 685 5482. </p>
<p>Thanks for your time. </p>
<p>Best Regards, 
<table cellpadding="0" cellspacing="0" border="0" style="background: none; border-width: 0px; border: 0px; margin: 0; padding: 0;">
<tr><td colspan="2" style="padding-bottom: 5px; color: #F2612C; font-size: 18px; font-family: Arial, Helvetica, sans-serif;">Madhu Mohan</td></tr>
<tr><td colspan="2" style="color: #333333; font-size: 14px; font-family: Arial, Helvetica, sans-serif;"><i>Operations Head - Canada</i></td></tr>
<tr><td colspan="2" style="color: #333333; font-size: 14px; font-family: Arial, Helvetica, sans-serif;"><strong>eTangerine Technologies</strong></td></tr>
<tr><td width="20" valign="top" style="vertical-align: top; width: 20px; color: #F2612C; font-size: 14px; font-family: Arial, Helvetica, sans-serif;">m:</td><td style="color: #333333; font-size: 14px; font-family: Arial, Helvetica, sans-serif;">+1 314-585-5482</td></tr>
<tr><td width="20" valign="top" style="vertical-align: top; width: 20px; color: #F2612C; font-size: 14px; font-family: Arial, Helvetica, sans-serif;">w:</td><td valign="top" style="vertical-align: top; color: #333333; font-size: 14px; font-family: Arial, Helvetica, sans-serif;"><a href="http://www.etangerine.org" style=" color: #1da1db; text-decoration: none; font-weight: normal; font-size: 14px;">www.etangerine.org</a>&nbsp;&nbsp;<span style="color: #F2612C;">e:&nbsp;</span><a href="mailto:madhum@etangerine.org" style="color: #1da1db; text-decoration: none; font-weight: normal; font-size: 14px;">madhum@etangerine.org</a></td></tr>
<tr><td colspan="2" style="padding-top: 5px;"><a href="https://www.facebook.com/etangerine/" style="border-width:0px; border:0px; text-decoration: none;"><img width="25" height="25" style="border: none; width: 25px; max-width: 25px !important; height: 25px; max-height: 25px !important;" src="http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/facebook_sig.png"></a>&nbsp;&nbsp;<a href="https://twitter.com/etangerine_org" style="border-width:0px; border:0px; text-decoration: none;"><img width="25" height="25" style="border: none; width: 25px; max-width: 25px !important; height: 25px; max-height: 25px !important;" src="http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/twitter_sig.png"></a>&nbsp;&nbsp;<a href="https://ca.linkedin.com/in/madhu-mohan-730a3222" style="border-width:0px; border:0px; text-decoration: none;"><img width="25" height="25" style="border: none; width: 25px; max-width: 25px !important; height: 25px; max-height: 25px !important;" src="http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/linkedin_sig.png"></a></td></tr>
</table><p>
